# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
 #     - name: Install Dependencies
 #       run: |
 #         sudo apt update
 #         sudo apt install -y gcc-10-m68k-linux-gnu make gcc flex bison && echo CPUS=$(nproc)

      - name: Build NetBSD bootloader
        run: |
          set +x
          set -e
          cd $GITHUB_WORKSPACE
          ./build-boot-NeXT.sh
          echo "DATE=$(date +%F-%H.%M.%S)" >> $GITHUB_ENV
          echo "USER_HOME=$HOME" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build/${{ env.DATE }}_${{ github.sha }}
          release_name: netbsd-boot-NeXT-${{ env.DATE }}-${{ github.sha }}
          # body: |
          #   Changes in this Release
          #   - First Change
          #   - Second Change
          draft: false
          prerelease: false

      - name: Upload aout bootloader to Release
        id: upload-release-asset-aout
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.USER_HOME }}/next/netbsd-obj/netbsd-boot-next.aout
          asset_name: netbsd-boot-next.aout
          asset_content_type: application/octet-stream

      - name: Upload macho bootloader to Release
        id: upload-release-asset-macho
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.USER_HOME }}/next/netbsd-obj/netbsd-boot-next.macho
          asset_name: netbsd-boot-next.macho
          asset_content_type: application/octet-stream

